-- ============================================================
-- schema.sql —— 建表脚本（Day 16 · 板块②）
-- 项目：meng-vibe-coding（出行规划小助手）｜ 后端区 cloud/
-- 数据库：PostgreSQL（CloudBase 控制台的「SQL 型数据库」）
-- ============================================================
--
-- 【这份文件是干什么的】
--   它只负责「把两张空表搭出来」。表里一行数据都没有 ——
--   灌数据是下一步 seed.sql 的事。两件事分开，是因为：
--     建表 = 定结构（偶尔改一次）
--     灌数据 = 填内容（以后经常改）
--   混在一起，每次改一条价格都要重新想一遍表结构。
--
-- 【⚠️ 这是 PostgreSQL 的脚本，不是 MySQL 的】
--   最初按 MySQL 写过一版，但 CloudBase 这个环境里能用的 SQL 数据库
--   是 PostgreSQL（控制台左侧「SQL 型数据库」→ PostgreSQL 管理）。
--   两者都叫 SQL，但口音不一样 —— 下面这些 MySQL 写法在这里
--   一个都用不了，已经全部换成 PostgreSQL 的说法：
--
--     MySQL 写法                      PostgreSQL 写法
--     ──────────────────────────────  ────────────────────────────────────
--     INT UNSIGNED AUTO_INCREMENT     INTEGER GENERATED BY DEFAULT AS IDENTITY
--     ENGINE=InnoDB                   没有这个概念（PG 只有一种存储引擎）
--     DEFAULT CHARSET=utf8mb4         没有这个概念（编码在建库时就定死了）
--     COLLATE=...                     同上
--     ENUM('en','play')               VARCHAR + CHECK（理由见「附一」）
--     COMMENT '...' 挂在列后面        COMMENT ON COLUMN ...（独立的语句）
--     UNIQUE KEY 名字 (列)            CONSTRAINT 名字 UNIQUE (列)
--     表尾 COMMENT='...'              COMMENT ON TABLE ...
--     ON DUPLICATE KEY UPDATE         ON CONFLICT ... DO UPDATE（在 seed.sql 里）
--
--   换的是「口音」，不是「要办的事」：两张表、字段类型、字段注释、
--   唯一约束、外键 —— 该有的一样不少。
--
-- 【怎么用】
--   1. 打开 CloudBase 控制台 → 左侧「SQL 型数据库」→ PostgreSQL 管理
--   2. 点左侧「SQL 编辑器」
--   3. 把本文件全文粘进去，执行
--   4. 成功的样子：一路成功提示，左侧「表」里多出 cities、places
--
-- 【执行顺序】
--   本文件必须先于 seed.sql 执行。理由：places 表里有一行外键指着 cities，
--   城市表还不存在时，数据库会拒绝建 places。
--
-- 【这份文件可以重复执行】
--   用的是 CREATE TABLE IF NOT EXISTS —— 表已经在了就整个跳过，不报错。
--   COMMENT ON 也是「重复执行没副作用」的（直接把旧注释覆盖掉）。
--   ⚠️ 但也正因为是 IF NOT EXISTS：如果你改了下面的字段定义再跑，
--      数据库不会帮你改已经存在的表。那种情况要走底部的「重置脚本」。
--
-- 【建在哪个 Schema 下】
--   控制台默认的 Schema 是 public。本文件不写前缀，就建在 public 里。
--   万一你的默认 Schema 不是 public，在最前面加一行：
--     SET search_path TO public;
--
-- 【本项目的数据出处（项目规矩 8.7）】
--   cities 的数据来源：app.js 的 CN_CITIES（370 个城市名）
--   places 的数据来源：app.js 的 CITY_HIGHLIGHTS（成都 6 条 + 重庆 6 条）
--   本文件只定义结构、不含任何数据，所以不涉及编造数值。
--
-- ============================================================


-- ------------------------------------------------------------
-- 表 1：cities —— 城市白名单
-- 存的是「程序认不认这个城市」。用户在页面填城市时，就是拿它校对。
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cities (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(32)  NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_cities      PRIMARY KEY (id),
  CONSTRAINT uk_cities_name UNIQUE (name)
);


-- ------------------------------------------------------------
-- 表 2：places —— 美食美景清单
-- 存的是「某个城市有哪些吃的、哪些玩的，参考价多少」。
-- 关联：places.city_id 指向 cities.id（一个城市 对 多条地点 = 一对多）
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS places (
  id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
  city_id     INTEGER      NOT NULL,
  name        VARCHAR(64)  NOT NULL,
  type        VARCHAR(16)  NOT NULL,
  price       INTEGER      NOT NULL DEFAULT 0,
  note        VARCHAR(255) NOT NULL DEFAULT '',
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_places           PRIMARY KEY (id),

  -- 联合唯一约束：同一个城市里，地点名不许重复。
  -- ⚠️ 它同时是「种子脚本能重复执行」的关键 ——
  --    seed.sql 靠它判断「这行已经存在」，才能做到有则更新。
  --    没有它，重复跑要么插出重复行、要么每次都报错。
  -- 另外它还顺便顶替了一个「单独给 city_id 建的普通索引」：
  --    索引最左边那列就是 city_id，按 city_id 单独查也能用它（最左前缀）。
  CONSTRAINT uk_places_city_name UNIQUE (city_id, name),

  -- 类别只能是 en 或 play —— 这是 PostgreSQL 版的「枚举」。
  CONSTRAINT ck_places_type      CHECK (type IN ('en', 'play')),

  -- 价格不许为负。
  -- （MySQL 版这里用的是 UNSIGNED，PostgreSQL 没这个修饰词，改用 CHECK）
  CONSTRAINT ck_places_price     CHECK (price >= 0),

  -- 外键：让数据库也强制「你插的地点必须指向一个真实存在的城市」。
  -- 插一个不存在的 city_id，会当场报错。
  -- 默认行为：想删掉一个还有地点的城市 → 会被拦住（这叫 RESTRICT）。
  --
  -- ⚠️ 如果执行时报外键相关的错，把下面这一行整行删掉再执行即可 ——
  --    其余部分完全不受影响，「关联」这件事依旧由 city_id 这个字段本身维系。
  CONSTRAINT fk_places_city      FOREIGN KEY (city_id) REFERENCES cities(id)
);


-- ============================================================
-- 字段注释
-- ============================================================
-- ⚠️ PostgreSQL 没有「把 COMMENT 写在列后面」这种写法，注释是独立语句。
--    好处是：想改注释不用动表结构，单独再跑一遍 COMMENT ON 就行。
--    这些语句重复执行也没问题（直接覆盖旧的）。
-- ============================================================

COMMENT ON TABLE  cities IS '城市白名单。数据来源：app.js 的 CN_CITIES。';

COMMENT ON COLUMN cities.id         IS '主键，自增。为什么不拿城市名当主键：名字可能被改（襄樊改襄阳），主键一改，所有指向它的记录都要跟着改；数字 id 没这个麻烦。';
COMMENT ON COLUMN cities.name       IS '城市名，如「成都」。括号里的 32 数的是字符不是字节 —— 一个汉字算一个字符，所以能存 32 个汉字。32 是留了余量：中国最长的市/盟名也就 5 个字（锡林郭勒盟）。';
COMMENT ON COLUMN cities.created_at IS '这行是什么时候进来的。用不带时区的 TIMESTAMP，而不是 TIMESTAMPTZ：前者「存什么读什么」，后者会按会话时区自动换算，排查数据时容易看花眼。';

COMMENT ON TABLE  places IS '美食美景清单。数据来源：app.js 的 CITY_HIGHLIGHTS。';

COMMENT ON COLUMN places.id         IS '主键，自增。';
COMMENT ON COLUMN places.city_id    IS '★关联字段★ 指向 cities.id，表示「这条地点属于哪个城市」。类型必须和 cities.id 一模一样（都是 INTEGER），否则表尾那个外键会建不上。';
COMMENT ON COLUMN places.name       IS '地点名，如「龙抄手（总店）」。最长的一条是「大熊猫繁育研究基地」9 个字，64 够用。';
COMMENT ON COLUMN places.type       IS '类别：en = 吃，play = 玩。取值与 app.js 里完全一致，不另造一套编码。写错值会被数据库当场拒绝（靠 ck_places_type 这个 CHECK 约束）。';
COMMENT ON COLUMN places.price      IS '参考价（元）。现有数据 0~70 全是整数，所以用 INTEGER 而不是 NUMERIC。⚠️ 注意：这是估算值，页面上必须标注。';
COMMENT ON COLUMN places.note       IS '给用户看的一句提示，如「学生票约 27 元，记得带学生证」。255 够用就不上 TEXT —— 不是省空间，是让数据库帮你兜住异常长的脏数据。';
COMMENT ON COLUMN places.created_at IS '这行是什么时候进来的。';


-- ============================================================
-- 附一：为什么 type 用 VARCHAR + CHECK，而不是 PostgreSQL 的原生 ENUM
-- ============================================================
-- PostgreSQL 确实有 ENUM，但要先写一句
--   CREATE TYPE place_type AS ENUM ('en', 'play');
-- 然后列定义写成 place_type。没选它，有三个现实原因：
--
--   ① CREATE TYPE 没有 IF NOT EXISTS —— 重复执行会报「类型已存在」，
--      得额外包一层 DO $$ ... EXCEPTION WHEN duplicate_object ... $$ 去兜。
--      为了「重复执行不报错」这条要求，白白复杂一大截。
--   ② 想加第三类（比如「住」）时，ENUM 只能用 ALTER TYPE ... ADD VALUE，
--      而且不能删值、不能改名，改起来很别扭；
--      换成 CHECK 约束就是「删掉旧约束、加个新约束」，一眼看得懂。
--   ③ 效果一样：写错值数据库照样当场拒绝。
--
-- 唯一的小代价：VARCHAR(16) 比 ENUM 多占一点点空间。
-- 而我们总共只有 12 行数据，这点差别完全无所谓。
-- ============================================================


-- ============================================================
-- 附二：为什么这两张表里没有这些字段
-- ============================================================
-- ・没有「省份」列
--   app.js 里没有这份数据。凭空编 370 个城市的省份会违反项目规矩 8.7
--   （数据必须有出处）。要加，先找一份有出处的名单，再加列。
--
-- ・没有「用户自填地点」相关的表
--   那是 Day 18/19 做 POST / DELETE /api/places 时的事，今天清单只要求两张核心表。
--
-- ・没有价目表（住宿 90/晚、吃 80/天…）
--   算钱必须留在浏览器本地（PRD 的 AC14：断网也能用）。
--   这份数据留在 app.js，不上云 —— 这就是「两块地」的纪律。
-- ============================================================


-- ============================================================
-- 附三：重置脚本（平时不要执行！）
-- ============================================================
-- 只有在「表结构要推倒重来」时才用。把下面两行的 -- 去掉，整段执行。
-- ⚠️ 顺序不能反：places 指着 cities，先删 cities 会被外键拦住。
--
-- DROP TABLE IF EXISTS places;
-- DROP TABLE IF EXISTS cities;
--
-- 删完再把本文件从上面重新执行一遍即可。
-- ============================================================
